matrix:
  include:
    - language: python
      python: 3.8
      script: ./test_parser.sh python parser_python.py

    - language: ruby
      script: ./test_parser.sh ruby parser_ruby.rb

    - language: csharp
      mono: latest
      script:
        - msbuild parser_dotnet/parser_dotnet.csproj
        - ./test_parser.sh parser_dotnet/Release/parser_dotnet
  
